### ISSUE TITLE
Customize colors used for dark mode

### ISSUE THREAD

**Issue by regularlabs** [jjranalli/nightwind#1]
Glad to see someone already had the idea to make this plugin :)

What would make it even more powerful is if you can override the color conversion.
So instead of relying on the automatic 'flipping' of the colors, be able to simply set your own colors for dark mode.

So essentially something like:
```
colors: {
  red: {
    100: '#ffe4e6',
    ...
    500: '#f43f5e',
    ...
    900: '#881337',
  },
},
dark: {
  colors: {
    red: {
      100: '#9f1239',
    ...
      500: '#fb7185',
    ...
      900: '#fff1f2',
    },
  },
},
```

You would then even be able to 'misuse' it to make `bg-red-500` not even be actual red in dark mode, but purple or whatever you want.

**Comment by regularlabs** [comment]
This would also give the ability to make the default white be a more gray in dark mode.

**Comment by jjranalli** [comment]
Glad you like Nightwind! Currently working on this feature, it should be added in the next update.

**Comment by regularlabs** [comment]
Awesome. If you need me to test things or want feedback, let me know.

**Comment by jjranalli** [comment]
Closing this as I've added this feature in 1.0.4. Check out the "Color mapping" section in the readme to see how it works, but it's very similar to how @regularlabs imagined it. Feedback is welcome!

**Comment by regularlabs** [comment]
Ok, great. Will test it out.

How come you chose to use the keyword `dark` for this, instead of `nightwind` for all the other stuff?

**Comment by jjranalli** [comment]
I felt it made more sense in this particular case, but I had mixed feelings about it. I also think it can be confusing when I've used `nightwind` everywhere else.

I'm about to push a hotfix in 1.0.5 and a new mapping option (for mixed mapping, you'll find it in the readme). And I'll probably change `dark` to `nightwind` there. Thanks for pointing it out!

**Comment by regularlabs** [comment]
I tried this:
```
		dark      : {
			colors: {
				white: 'gray.900',
				black: 'gray.50',
				gray  : {
					50 : 'gray.800',
					100: 'gray.700',
					200: 'gray.600',
					300: 'gray.500',
					400: 'gray.400',
					500: 'gray.300',
					600: 'gray.200',
					700: 'gray.100',
					800: 'gray.50',
					900: 'gray.50',
				}
			},
		},
```
Black and white are working ok.
But the gray shades output css like:
```
.dark .bg-gray-800, .dark .bg-gray-900, .dark .hover\:bg-gray-800:hover, .dark .hover\:bg-gray-900:hover {
    background-color: rgba(NaN,NaN,80,var(--tw-bg-opacity));
}
```

**Comment by jjranalli** [comment]
This should be fixed in 1.0.5. Try updating (and switching `dark` to `nightwind)`

**Comment by regularlabs** [comment]
Wow, lighting fast fix. And yes, all working now! 👍

**Comment by regularlabs** [comment]
Just to be clear:
I (probably) want all colors to be flipped by default where 50-900 becomes 50-900.
Like:
```
gray : {
	50 : 'gray.900',
	100: 'gray.800',
	200: 'gray.700',
	300: 'gray.600',
	400: 'gray.500',
	500: 'gray.400',
	600: 'gray.300',
	700: 'gray.200',
	800: 'gray.100',
	900: 'gray.50',
},
```
So that means I will need to add the above for all my colors?

**Comment by regularlabs** [comment]
I mean, could be an idea to add something like:
```
colorShades : {
	50 : 900,
	100: 800,
	200: 700,
	300: 600,
	400: 500,
	500: 400,
	600: 300,
	700: 200,
	800: 100,
	900: 50,
},
```
