### ISSUE TITLE
Allow fixedClass (or another option) work for the element and its descendants

### ISSUE THREAD

**Issue by bep** [jjranalli/nightwind#10]
My observations tells me that `fixedClass` does not get applied to its descendants, so the `text-gray-800` will still be shifted when going to night mode:

```html
<div class="fixedClass bg-gray-900">
<div class="text-gray-800"></div>
</div>
```

That is useful on its own, but I suspect a common use case would be to have an entire block that you would want to ignore.

In my use case, I have a site

* With a blog and documentation section that looks great with Nightwind in dark mode
* With a home page with very specific colours that kind of looks like a Christmas tree with Nightwind in dark mode

**Comment by jjranalli** [comment]
Totally agree about the need of a fixedClass that prevents dark-mode switching to its children elements.

I think both implementations are useful though, so I believe the best approach would be having two separate fixed classes - one targeting the same element, the other targeting children elements.

I admit I'm a bit tempted to give the new fixedClass `prevent-christmas` as default name.

**Comment by jjranalli** [comment]
Closing the issue as the feature has been added in 1.1.10. The default class name is `nightwind-prevent-block`, while details about the configuration options can be found in the [related section in the docs](https://github.com/jjranalli/nightwind#the-nightwind-prevent-class).
