### ISSUE TITLE
parameter for toggeling a specific theme

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [jjranalli/nightwind#13]
Is there something like a parameter that can be passed to the toggle function like `nightwind.toggle(light)` for only enabeling a specific theme?

**Comment by jjranalli** [comment]
Thanks for opening the issue! This is not currently possible, but it seems a reasonable functionality. Will probably add it in the next release :)

**Comment by jjranalli** [comment]
Closing as the issue has been fixed in 1.1.12

**Comment by HAUDRAUFHAUN** [comment]
Ok, thanks man :)
