### ISSUE TITLE
How do I toggle between modes?

### ISSUE THREAD

**Issue by thedivtagguy** [jjranalli/nightwind#17]
Hi! Thank you for the great plugin!
I'm trying to incorporate a toggle switch for my website, which is built with Hugo. The examples in the documentation are for React and Next.js so I'm having trouble understanding what I can do to have a simple toggle switch. This is what I have: 

In the menu: 
```
  <button id="switchTheme" class="h-10 w-10 flex justify-center items-center focus:outline-none text-yellow-500">
                                <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" clip-rule="evenodd"></path></svg>
                            </button>
```

And this is followed by: 

```
<script>
    document.getElementById('switchTheme').addEventListener('click', function() {
        let htmlClasses = document.querySelector('html').classList;
        if (localStorage.theme == 'dark') {
            htmlClasses.remove('dark');
            localStorage.removeItem('theme')
        } else {
            htmlClasses.add('dark');
            localStorage.theme = 'dark';
        }
    });
</script>
```
But this does nothing. Can someone help me understand how I can write this toggle? I'm not using any JS framework.

**Comment by jjranalli** [comment]
Hey there! Thanks for opening the issue. Your code looks fine to me at a first glance. As long as the 'dark' class is getting added/removed correctly to your root element, Nightwind should work as expected.

And just so I better understand the issue, is Nightwind not working at all, or are you just having problems with the toggle? In other words, if you manually add the 'dark' class do you see the colors switch?

If not, there may be a problem in how you implemented Nightwind, namely your tailwind.config.js. Could you please also share you tailwind.config.js? Thanks!

**Comment by thedivtagguy** [comment]
Thanks for the quick response! I tried adding the `dark` class manually and that works fine, the elements do get inverted. The code I've added gets included after the body tag on each page so I'm confused as to why this isn't working. This code is included in my `head.html` partial, so the script is being included on each page along with the toggle. My config is below: 

```
module.exports = {
    theme: {
        extend: {}
    },
    variants: {},
    plugins: [
        require('@tailwindcss/typography'),
    ],
    darkMode: "class",
    // ...
    plugins: [require("nightwind")]
}
```

**Comment by thedivtagguy** [comment]
This seems to be working! 
```
  const themeSwitch = document.getElementById('switchTheme');
    themeSwitch.addEventListener('click', () => {
        document.body.classList.toggle('dark');
    });
```

Thank you for your help and again, for a wonderful plugin.

**Comment by jjranalli** [comment]
Glad you managed to work it out! 😁
