### ISSUE TITLE
Add support for shadow colors

### ISSUE THREAD

**Issue by regularlabs** [jjranalli/nightwind#2]
Is it possible to add support for shadow colors?
Or is this already possible via the config?

**Comment by jjranalli** [comment]
This was not currently planned, as Tailwind uses black by default for all box shadows. If it works in your case, you could use the rings as an alternative (by setting them up in the config first).

However, I had a quick look at this matter and will consider adding it in the future. Could you share more details on how you normally set up your coloured shadows on Tailwind, and how you'd expect it to work on Nightwind?

**Comment by regularlabs** [comment]
Well, this would indeed only concern the black shadows being converted to white, in my case.
I have now solved it by adding this to my scss:
```
.dark {
	.shadow {
		--tw-shadow: 0 1px 3px 0 rgba(255, 255, 255, 0.1), 0 1px 2px 0 rgba(255, 255, 255, 0.06);
	}

	.shadow-sm {
		--tw-shadow: 0 1px 2px 0 rgba(255, 255, 255, 0.05);
	}

	.shadow-md {
		--tw-shadow: 0 4px 6px -1px rgba(255, 255, 255, 0.1), 0 2px 4px -1px rgba(255, 255, 255, 0.06);
	}

	.shadow-lg {
		--tw-shadow: 0 10px 15px -3px rgba(255, 255, 255, 0.1), 0 4px 6px -2px rgba(255, 255, 255, 0.05);
	}

	.shadow-xl {
		--tw-shadow: 0 20px 25px -5px rgba(255, 255, 255, 0.1), 0 10px 10px -5px rgba(255, 255, 255, 0.04);
	}

	.shadow-2xl {
		--tw-shadow: 0 25px 50px -12px rgba(255, 255, 255, 0.25);
	}
```
So pretty much replaced `0, 0, 0` with '255, 255, 255'.

**Comment by jjranalli** [comment]
Got it, seems reasonable. I'll keep the issue open meanwhile I look into adding this by default.

**Comment by regularlabs** [comment]
PS: To be able to make overrides work, like `class="shadow-lg dark:shadow-sm"` I have had to do this:
```
.dark {
	.shadow {
		--tw-shadow: 0 1px 3px 0 rgba(255, 255, 255, 0.1), 0 1px 2px 0 rgba(255, 255, 255, 0.06);
	}

	.shadow-sm {
		--tw-shadow: 0 1px 2px 0 rgba(255, 255, 255, 0.05);
	}

	...

	.shadow-2xl {
		--tw-shadow: 0 25px 50px -12px rgba(255, 255, 255, 0.25);
	}

	.dark\:shadow {
		--tw-shadow: 0 1px 3px 0 rgba(255, 255, 255, 0.1), 0 1px 2px 0 rgba(255, 255, 255, 0.06);
	}

	.dark\:shadow-sm {
		--tw-shadow: 0 1px 2px 0 rgba(255, 255, 255, 0.05);
	}

	...

	.dark\:shadow-2xl {
		--tw-shadow: 0 25px 50px -12px rgba(255, 255, 255, 0.25);
	}
}
```

**Comment by jjranalli** [comment]
Closing this as adding support for shadow colors isn't a priority at the moment.
