### ISSUE TITLE
How to use with CRA ?

### ISSUE THREAD

**Issue by Djiit** [jjranalli/nightwind#20]
Hey folks,

Awesome work! I'm using it with NextJS and it's working like a charm. I'd like to use it on a new CRA project (followed this: https://tailwindcss.com/docs/guides/create-react-app) but it's not working (no dark mode, and the toggle function does nothing).

Did I miss anything ? Thanks

**Comment by jjranalli** [comment]
Hey there! Could you provide a repo to reproduce the issue so I can look into it? Thanks!

**Comment by Djiit** [comment]
Hey! Yep, have a look at this one : https://github.com/Djiit/nightwind-cra

**Comment by Djiit** [comment]
Last thing I tried was to copy the init function directly on the index.html . Not working :( Maybe I'm missing something obvious and/or I need a Theme manager or something... Tailwind is loaded (see the red text).

**Comment by jjranalli** [comment]
Everything seems to be set up correctly, and Nightwind works fine on my end! Classes are added correctly, including the init you manually inserted in index.html.

However, it is quite hard to see it working as you chose `text-red-500` on the toggle which gets switched to `text-red-400` in dark mode, and is very hard to distinguish on a white background. The background on the other hand doesn't switch because you need to specify a bg color somewhere (`bg-white` on body?) otherwise Nightwind doesn't have anything to switch from/to.

Let me know if everything also works on your end!

**Comment by Djiit** [comment]
Oh wow I must have been tired ahah. Alright, according to you is it the best way to add it ? (specificaly the way I copied/pasted the init code in index.html ?)

If yes, I'm happy to open a PR to document it in the README.

Thanks!

**Comment by jjranalli** [comment]
No worries ahah I can relate! Anyway, the way I would initialise Nightwind would be adding the init() script in the head importing it from the package. The reason why it should be in the head is that it would prevent the white flash on reload while in dark mode.

Personally, In React I'd use something like React Helmet and add it in index.tsx using `dangerouslySetInnerHTML`. Similarly as it's documented [here](https://github.com/jjranalli/nightwind#initialization)

I'm honestly not sure if further documentation is needed on how to initialise Nightwind, as it really depends on the app and framework used. I can only think of an example with plain html, that could make sense.

But if you feel like it's not detailed enough or is lacking crucial information, feel free to let me know or open a PR :)

**Comment by Djiit** [comment]
Proposed a tiny change. Yup, the "default" example is ok but uses `Head` (probably from Next.js ?) and I was confused at first 😅

**Comment by jjranalli** [comment]
Yes you're indeed correct. I'll also have to edit the Next example due to the new (very nice) Script component in Next 11, so it's good to have a separate example for React. Thanks for the PR, will review it asap!

**Comment by Djiit** [comment]
Oh yeah, was watching the show too ahah
