### ISSUE TITLE
Edit conversion in color weights

### ISSUE THREAD

**Issue by jjranalli** [jjranalli/nightwind#3]
Just to be clear:
I (probably) want all colors to be flipped by default where 50-900 becomes 50-900.
Like:
```
gray : {
	50 : 'gray.900',
	100: 'gray.800',
	200: 'gray.700',
	300: 'gray.600',
	400: 'gray.500',
	500: 'gray.400',
	600: 'gray.300',
	700: 'gray.200',
	800: 'gray.100',
	900: 'gray.50',
},
```
So that means I will need to add the above for all my colors?

_Originally posted by @regularlabs in https://github.com/jjranalli/nightwind/issues/1#issuecomment-749320139_

**Comment by jjranalli** [comment]
@regularlabs I'll consider this, probably for 1.0.6. I want to check some things first, but it shouldn't take long.
 
Regarding your other comment, I don't think I'll add a default customisable option for this. Every color is different in tailwind and swaps differently, so if one wants to customise them it would probably be on a color basis, thus would be better to use mapping or overrides. However, if enough people feel the need to a custom default weights, I may consider adding it in the future.

**Comment by regularlabs** [comment]
Yeah, the idea would be to be able to set the default mapping...
But using overrides works too. Just more code in the config file.

**Comment by jjranalli** [comment]
Closing the issue as it has been implemented in 1.0.6

**Comment by regularlabs** [comment]
Hmmm, thanks for the stuff you did on this and the changes you made.

But, and you're going to hate me for this, I found that with the colors, I do want to keep the 500 as the middle color. As that is the most saturated base color. So changing that to 400 in dark mode, makes it all washed out. This is fine with gray, but not with the other colors. I assume that that would be the same for most color pallets.

So now, to get around it, I have had to add overrides for all my colors, except gray 😁

**Comment by jjranalli** [comment]
On the contrary, this is a rather interesting point and is exactly the kind of things I was considering before updating. 

I've checked the tailwind palette, and while the 500 isn't always the most saturated color it may definitely be for some of them. Also, I personally don't notice the same problem of washed-out colors, and they seem to be consistent with the results I was expecting (higher weights yield higher contrast in both modes, as you can see here).
![colorweights](https://user-images.githubusercontent.com/39241410/102922374-3af34b80-448e-11eb-941b-b01754e8e9ff.jpg)

Thus, I don't see a particular issue in not having a default color that remains exactly the same between modes.

However, this may be why setting the default mapping weights could be helpful in some cases. I will consider it.

**Comment by regularlabs** [comment]
Yup, I agree with all you said.
