### ISSUE TITLE
How to use this with vanilla js

### ISSUE THREAD

**Issue by asimpletune** [jjranalli/nightwind#35]
Hi, congrats on the plugin and the demo website. They're super beautiful.

I was interested in using nightwind, but it's for a small site that's just a few pages. I don't plan on using react or anything like that. I'm also a backend developer, so my experience with the latest front end frameworks is 0. 

How do I use nightwind with just normal js?

**Comment by jjranalli** [comment]
Thanks for taking the time to write this up @d3cline! If you're up to it, it would be great if you could open a PR to add the snippet in the [example section](https://github.com/jjranalli/nightwind#examples) of the readme.
