### ISSUE TITLE
Add support for Typescript

### ISSUE THREAD

**Issue by ajonp** [jjranalli/nightwind#4]

**Comment by jjranalli** [comment]
Closing this as there is no plan to add typescript support at the moment.

**Comment by jayakornk** [comment]
Hi @jjranalli , first thanks for an awesome plugin.

I just create a simple type declaration file just for my own project but I think sharing this with you could maybe help the others as well.

Would you mind add `helper.d.ts` beside `helper.js`?

```ts
/**
 * To initialize nightwind, add the following script tag to the head element of your pages.
 *
 * ```
 * import nightwind from "nightwind/helper"
 *
 * export default function Layout() {
 *   return (
 *     <>
 *       <Head>
 *         <script dangerouslySetInnerHTML={{ __html: nightwind.init() }} />
 *       </Head>
 *       // ...
 *     </>
 *   )
 * }
 * ```
 */
export declare function init(): string;
/**
 * Similarly, you can use the toggle function to switch between dark and light mode.
 * ```
 * import nightwind from "nightwind/helper"
 *
 * export default function Navbar() {
 *   return (
 *     // ...
 *     <button onClick={() => nightwind.toggle()}></button>
 *     // ...
 *   )
 * }
 * ```
 */
export declare function toggle(): void;
```

Feel free to change the wording and content.

**Comment by jjranalli** [comment]
Thanks @jayakornk, will add this in the next release!

**Comment by kotx** [comment]
Hey, any update on this? This doesn't seem to have been added.

**Comment by jjranalli** [comment]
@kotx Will release a new version later today with an updated declaration file

**Comment by joshcomley** [comment]
Hi there - the definition file doesn't appear to be in the latest release, is it perhaps ignored on publish somehow?

**Comment by wottpal** [comment]
Same issue!

**Comment by szamanr** [comment]
@jjranalli can we please add the definition file? a PR is up and has been for 3 months!

**Comment by CommanderStorm** [comment]
FYI: `@types/nightwind` is now avaliable.
You can install it via

```
npm install --save-dev @types/nightwind
```
