### ISSUE TITLE
Picking up `even:` modifier

### ISSUE THREAD

**Issue by timvink** [jjranalli/nightwind#44]
nightwind is awesome! Thanks for developing this plugin and the clear documentation 👏🏻 

I'm using a table adapted from [this example table](https://www.section.io/engineering-education/implementing-dark-mode-using-tailwind-css/), which breaks on the even rows.

Relevant line of HTML:

```html
<tr class="border-b border-gray-200 even:bg-gray-50 hover:bg-gray-100">
```

Which looks fine in light mode:
![image](https://user-images.githubusercontent.com/5570380/142776786-c8d536fc-ea1d-4a7f-9d76-4267a61f0238.png)

But breaks in dark mode on the even rows:

![image](https://user-images.githubusercontent.com/5570380/142776804-ee3b20c9-282b-4574-852d-01a3aaa1b345.png)

I don't have a workaround yet, no luck yet with adding a class `dark:even:bg-gray-700`.

**Comment by timvink** [comment]
FYI, the workaround is not using the `even:` operator, but instead writing some javascript to insert a class on every even row (here's an [example](https://github.com/timvink/project-monitor/commit/2bde4a7b5736109e8c493124062f4e3d5e27b835))

**Comment by jjranalli** [comment]
Hey @timvink, glad to hear you like Nightwind 😁

About your issue, can you confirm me that you've added the `even` variant in the nightwind config in `tailwind.config.js`? It looks like nightwind is not generating the dark class you need. It should look something like this:

```js
// tailwind.config.js
module.exports = {
  // ...
  variants: {
    nightwind: ["focus", "even"], // Add any Tailwind variant
  }
}
```

If this doesn't work, the quickest way for me to solve this is probably to have a look at a repro. Let me know!

**Comment by timvink** [comment]
Ahhh, I did miss that. I'm also new to tailwindcss. Thanks for the pointer, works perfectly!
