### ISSUE TITLE
Tailwind 3.0 typography breaks when nightwind dark mode is enabled

### ISSUE THREAD

**Issue by mtergel** [jjranalli/nightwind#45]
I've updated to tailwind and typography plugin.

```
"@tailwindcss/typography": "^0.5.0",
"nightwind": "^1.1.12",
"tailwindcss": "^3.0.0"
```

Breaks on the latest release when 
```
  nightwind: {
     typography: true,
  },
```
this option is enabled.

```
Tailwind CSS: Unexpected token u in JSON at position 0
SyntaxError: Unexpected token u in JSON at position 0

/nightwind/src/index.js:310:36
```

**Comment by quick007** [comment]
The package doesn't technically support v3, there should be a warning like this:
![image](https://user-images.githubusercontent.com/69743171/146702202-e794da64-44e9-4229-8c50-545dc03a1f95.png)

**Comment by mtergel** [comment]
okey
