### ISSUE TITLE
add a changelog

### ISSUE THREAD

**Issue by jbolda** [jjranalli/nightwind#5]
👋 

This has been a lovely experience to quickly get a dark mode set up and running! In debugging a flash of styles in the dark mode switch, I went looking to see what has been changed since my version was outdated. It would be very helpful if you had a changelog to read for these situations.

Thanks again for your work here!

**Comment by jjranalli** [comment]
Glad to hear you're enjoying Nightwind!

And thanks for bringing this up, I've been thinking about adding a changelog for a while. Will do it later today!

**Comment by jjranalli** [comment]
Closing this as I've added the [Changelog](https://github.com/jjranalli/nightwind/blob/main/CHANGELOG.md).
