### ISSUE TITLE
Custom color mapping with single value custom colors 

### ISSUE THREAD

**Issue by stenanderssen** [jjranalli/nightwind#53]
Firstly I wanted to say that Nightwind is a really awesome plugin for Tailwind. Keep up the good work! Thank you for your time and effort.

I am currently trying to use Nightwind in order to autmatically switch every used color in the HTML when the user switches to dark mode. In Tailwind I translated our design system to the Tailwind config. 
Our design system comprises brand and application colors. Brand colors are given in 50 to 900 values. Application colors reference a single color value from the brand colors like so:

```
theme: {
  colors: {
    blue: {
    …
    900: '#aHexColor'
    }
    primary: blue.900
  }
}
```

The design system is very opinionated so that the dev doesn't have to think about applying the correct styling in code. In concept a dev should only use application colors like primary or secondary without having to worry about color scales. In Nightwind I want to only automatically switch between application colors. Hence I disabled the color scaling like so:

```
colorScale: {
    50: 50,
    100: 100,
    200: 200,
    300: 300,
    400: 400,
    500: 500,
    600: 600,
    700: 700,
    800: 800,
    900: 900,
}
```

Then I wanted to introduce a custom color mapping in Nightwind referencing the primary color from Tailwinds colors config:

```
colors: {
  primary: blue.200,
}
```

But as far as I understand this is not working in Nightwind so I have to implement this workaround:

```
colors: {
  blue: {
    900: blue.200,
  }
}
```

As I think this color structure is not uncommon in a modern design system I wanted to ask if it is possible in Nightwind to reference custom color names ('primary') added in the Tailwind color config so that Nightwind works with single color values? Help is much appreciated 🙏

Thank you!

**Comment by jjranalli** [comment]
Hey, really glad to hear you like Nightwind! ❤️ 

As far as I understand the behaviour you intend to implement (color mappings for custom color classes) should already be supported by Nightwind so I'm not sure why it's not working in your case. Could you provide a minimal repo to reproduce the issue so I can look into it?

**Comment by stenanderssen** [comment]
Thank you for the quick response! I created a simple repo for you. I hope now my issue gets clearer.
https://github.com/stenanderssen/nightwind-color-mapping-issue

If you run the repo both text blocks should be in the same color and the same background. However the upper section is not influenced by Nightwind although dark mode is enabled.

**Comment by stenanderssen** [comment]
Thank you for resolving this issue. I will implement your proposed workaround until there is a better solution available ;)
I am looking forward to the next releases of Nightwind! Thank you for your quick and clear responses!
