### ISSUE TITLE
Update npm for Tailwind 3

### ISSUE THREAD

**Issue by d3cline** [jjranalli/nightwind#54]
I did a `--force` install of nightwind into tailwind 3 and it is working good, please update the package manager and anything else to work with tailwind 3, all those classes are too tedious we need nightwind still

**Comment by samueljim** [comment]
bump

**Comment by cceglia** [comment]
bump

**Comment by saschagysel** [comment]
I am getting this error when installing on a fully updated Laravel 9 with updated Tailwind, I think it is connected with this issue.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: tailwindcss@3.0.23
npm ERR! node_modules/tailwindcss
npm ERR!   dev tailwindcss@"^3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^2.0.0" from nightwind@1.1.12
npm ERR! node_modules/nightwind
npm ERR!   nightwind@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by quick007** [comment]
I made #48 but the author wants to support JIT, which this doesn't. I've moved to https://github.com/crswll/tailwindcss-theme-swapper as it's actively maintained, the author is more active on discord (and can provide support in the tailwind plugins channel.) While it takes a bit longer to set up, it's far more worth it in the long run.
