### ISSUE TITLE
Nightwind is unusable.

### ISSUE THREAD

**Issue by quick007** [jjranalli/nightwind#63]
When tailwind 3.0 came out, I started using crwsll's theme swapper on my projects. When I came back to do some maintenance on what is essentially my portfolio site, I updated it to nextjs 12 and noticed I was having super long hot refresh times (like >1.5 seconds). I removed some things and tried to find the problem, and finally, I removed nightwind. The improvement? **15 times faster**. That's from 1.5 seconds on the low end to constant sub 1/10th of a second refresh. Until nightwind gets the same treatment as tailwindcss (jut in time compilation), I can't use this package anymore.

**Comment by bep** [comment]
@quick007 I don't maintain this project, but you should consider your way communication, I suspect your tone and esp. your headline ("Nightwind is unusable.") is not very motivational in the way of improving this situation.

Tailwind 2 had 2-3 second rebuilds, which was fine in development mode as you rarely needed rebuilds. I would never have used the word "unusable" about Tailwind 2.

**Comment by quick007** [comment]
Looking back at this, I probably could've phrased this better and proposed solutions rather than just complaining and not highlighting problems.

**Comment by jjranalli** [comment]
Appreciate you writing this @quick007, and no hard feelings on my end. It's not like I don't understand your frustration either, I wish I had more time to dedicate to this package and follow up with all the issues but maintaining even a relatively small package like this can take a considerable amount of effort and time, which unfortunately I didn't have on my hand.

That said, I'm planning to get back on nightwind soon to fix all unsolved issues. Please look forward to it!
